name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-candidates-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-candidates-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-candidates-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-candidates-wrapper-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Perform all tests
        run: ./gradlew -stacktrace --parallel check
